import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/navbar";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import { Footer } from "@/components/footer/footer";
import { LanguageProvider } from "@/lib/i18n/language-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fashion Shop | Shopify Headless Next",
  description: "Generated by Shopify Headless Next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LanguageProvider>
          <NextTopLoader
            showSpinner={false}
            color="#000"
          />
          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
